[workspace]
members = [
    "auto_crossing", "basic/borrowing",
    "basic/compound_types",
    "basic/constants",
    "basic/control_flow",
    "basic/functions", "basic/mut_borrowing",
    "basic/mutability", "basic/ownership",
    "basic/scalar_types",
    "basic/shadowing",
    "examples/factorial", "examples/prime_numbers",
    "hello_cargo",
]

resolver = "3"
